var emobiliarios = [
    {
        nome:"mesa de estar",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/sof1.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Poltrona de Estar",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/sof3.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"sala"
    },
    {
        nome:"Poltrona de Estar",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/sof2.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"sala"
    },
    {
        nome:"Liquidificador Express",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/liq2.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"cozinha"
    },
    {
        nome:"Liquidificador normal",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/liq1.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"cozinha"
    },
    {
        nome:"Peso 50KG",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/peso1.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"peso"
    },
    {
        nome:"Mesa Refinada",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/mesa1.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Mesa TiTánica",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/mesa2.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Banca Cabeceira",
        preco:"394.599",
        avaliacao:3,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/mesa3.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"quarto"
    },
    {
        nome:"Cabeceira Noturna",
        preco:"394.599",
        avaliacao:5,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/mesa4.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Cadeira Gamer",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/cad2.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"quarto"
    },
    {
        nome:"Cabeceira de Escritórios",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/cad1.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Cadeira de Escritório",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/cad5.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"escritorio"
    },
    {
        nome:"Lensol Turco",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/len2.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"quarto"
    },
    {
        nome:"Lensol Linha",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/len4.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"quarto"
    },
    {
        nome:"Lensol Algodão",
        preco:"394.599",
        avaliacao:4,
        lugares:{
            quarto:2,
            escritorio:3,
            sala:4,
            outros:10
        },
        img:"/img/len3.jpg",
        id:Math.round(Math.random()*100000000000000*Math.random()*753),
        tipo:"quarto"
    },


]
export default emobiliarios;